apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}